version: '3.1'

services:
  api:
    build: ./
    command: su -c "python /api/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    env_file:
      - ./dev.env

  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: olist
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass123

volumes:
  pgdata: {}
