# Generated by Django 2.0.4 on 2018-05-15 14:07

from django.db import migrations, models
import django.utils.timezone
import telephony.services.call_event_data


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('en', 'Ended'), ('st', 'Started')], db_index=True, default='st', max_length=2)),
                ('call_id', models.PositiveIntegerField(db_index=True, default=telephony.services.call_event_data.get_new_call_id)),
                ('source', models.CharField(blank=True, max_length=11, null=True)),
                ('destination', models.CharField(blank=True, max_length=11, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Call Event',
                'verbose_name_plural': 'Call Events',
            },
        ),
    ]
