# Generated by Django 2.0.4 on 2018-05-14 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callevent',
            name='call_id',
            field=models.PositiveIntegerField(db_index=True, default=uuid.uuid4),
        ),
    ]
