# Generated by Django 2.0.4 on 2018-05-15 16:30

from django.db import migrations, models
import telephony.services.call_event_data


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callevent',
            name='call_id',
            field=models.PositiveIntegerField(default=telephony.services.call_event_data.get_new_call_id),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='event_type',
            field=models.CharField(choices=[('en', 'Ended'), ('st', 'Started')], default='st', max_length=2),
        ),
        migrations.AddIndex(
            model_name='callevent',
            index=models.Index(fields=['call_id', 'event_type'], name='telephony_c_call_id_093c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='callevent',
            index=models.Index(fields=['call_id', 'event_type', 'source', 'created'], name='telephony_c_call_id_e1b874_idx'),
        ),
    ]
